% Tracking work
%
% see MartinTracking folder in matlab folder for his files
% need to figure out how to use these
% Files TrackFinSei_1.dat, _2.dat, and _3.dat are the c3d outputs
% finTracks.mat is my output already put into matlab

clear all
clc
path = 'e:\score\2015\c3d\';
matpath = 'e:\score\2015\matlab\';
addpath(genpath(matpath));

% try playing with the .m files using TrackMinke.dat file in \MartinTracking
% PAMtracker19Aug2015.m is main file with all the inputs, etc.

% GenTracks.m       is function to track localizations using Indat
% PloIndTkDetails.m is function to plot individual track with details
%                       of ICI and est. speed
% PlotAllValidTracks.m is function to plot all tracks generated by the
%                       PAM tracking
% ReadC3Dlocs.m     is function to read individual model based localizations text files


%% Taking Steve's PAMtracker19Aug2015.m script and making my own with my paths, etc

place=input('Tracking on PMRF(1), SCORE(2), or other(3) ?  ');
% enter 1 2 or 3 - always 3, but fun new function!
RunPath=('e:\score\2015\c3d\');
cd (RunPath)
load('phones.mat');
phInfo=[phones.phone phones.lat phones.lon];  %placeholder for hydrophone sensor locations (unable to provide PMRF phone locations here)

% What is in this param file???
% will use these minke params for now, but may have to modify them
DeltaDSCmax = 3.5;
DeltaLatmax = 0.03;
DeltaLonmax = 0.03;
DeltaTmax = 2400;

prior=input('Use previously tracked info?  Yes(1)/No(0)  ');
if prior==1;
    if trackWhat==1, [matfilenam, matpathnam]=uigetfile('MinkeTracks.mat', 'select the minke .mat file'); end
    cd (matpathnam)
    load (matfilenam, 'vTk', 'vTkICI','Indat', 'DeltaTmax', 'InDir', 'tvcnt'); %this will load the vTk nested struct
    %TkParams
    cd (RunPath)
    %plot all of the valid tracks over time
    [vTk,startTim,endTim]=PlotAllValidTracks(place, phInfo, Indat, vTk);
else %create new (or changed track parameter values) track the localizations provided
    %read in localization data, ascii text file
    [Indat, RunPath, InDir, filenam, pathnam]=ReadC3Dlocs(place, RunPath); % this lets you select one
    %     if trackWhat==1, save IndatFinSei Indat, end;    %save the input data to .mat file
    save(['Indat' filenam(1:end-4) '.mat'],'Indat')
    minNumEle=0;
    cd(RunPath);
    %GenTracks is the function that actually creates the tracks from the
    %localizations
    [vTk, vTkICI, TrackStats, tvcnt, ICI,ICIcor, ICIt, ICItcor, spdICI]=GenTracks(InDir, DeltaTmax, DeltaLatmax, DeltaLonmax, RunPath, filenam);
    [vTk,startTim,endTim]=PlotAllValidTracks(place, phInfo, Indat, vTk);    %plot all tracks generated over time
    cd (InDir);
    %save matlab structure and data from tracking run
    save(['vTk' filenam(1:end-4)], 'vTk', 'vTkICI', 'place', 'InDir',...
        'Indat', 'tvcnt', 'DeltaTmax', 'DeltaLatmax', 'DeltaLonmax')
    cd (RunPath)
end

%% FOR PLOTTING INDIVIDUAL TRACK DETAILS (lat/lon and subplots for call
% intervals and estimated speed based upon movement and time between calls

cd(InDir);
status=0;
plotIndTk = 1;
plotN=input('Enter track # for single plot and IDI plot ');

while plotIndTk==1
    ICI=vTkICI(plotN).ICI;
    ICIcor=vTkICI(plotN).ICIcor;
    ICItcor=vTkICI(plotN).ICItcor;
    spdICI=vTkICI(plotN).spdICI;
    [status]=plotIndTkDetails(vTk,vTkICI, tvcnt, phInfo, place, plotN, ICI, ICIcor, ICItcor, spdICI);
    plotN=input('Plot more tracks details?  Enter track #/No(0)  ');
    disp(' ');
    if plotN==0, plotIndTk=0; end
    if plotN>0, plotIndTk=1; end
end



